version: '3.4'

services:
  petsapp:
    image: petsapp
    build: .
    links: 
      - mongo
    ports:
      - 3000:3000
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017-27019"
    volumes:
      - ./data:/data/db
