version: "3"
services:
  backend:
    image: node:12.18-alpine
    command: yarn server
    ports:
    - "3000:3000"
    working_dir: /app
    volumes:
    - .:/app
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/pets
      BACKEND_URL: http://localhost:3000
    depends_on:
    - mongo

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - mongodb:/data/db

volumes:
  mongodb:
    driver: local
    